cluster_shield:
  log_level: debug

  features:
    admission_control:
      enabled: true

    container_vulnerability_management:
      enabled: true

    audit:
      enabled: true

    posture:
      enabled: true
